export const rooms = [
  {
    name: ["Shizukana", " 静かな"],
    price: 115000,
    details:
      "Peaceful rest in a high-quality space― Through the entrance, you will find a living room with a high atrium. Large windows let in plenty of sunlight, creating a luxurious and open space. Outside the window, the unobstructed expanse of the sky changes moment by moment. Spend a relaxing time in the majestic nature.",
    properties: [
      "20 m²",
      "Balcony",
      "Box spring bed",
      "Flat-screen TV",
      "Room safe",
      "Wireless internet",
      "Shower / WC",
      "Hair dryer",
      "Larch furniture",
      "Real wooden floor",
      "Under-floor heating",
      "Non-smoking room",
    ],
    homePageUrl: "/images/shizu1.",
    extraImages: ["/images/shizu2.", "/images/shizu3."],
  },
  {
    name: ["Hofu", "豊富"],
    price: 150000,
    details:
      "Imagine snuggling up in the soft box spring bed in your cosy 20 m2 superior double room. At last you can stretch out the tired legs that have given their all during a day’s hiking or skiing. You can breathe the scent of larch and enjoy the warmth of the wooden floor. When you look out of the window or step onto the balcony, there's a wonderful view of Hinterglemm to savour. You can't help but sleep well here!",
    properties: [
      "20 m²",
      "Balcony",
      "Box spring bed",
      "Flat-screen TV",
      "Room safe",
      "Wireless internet",
      "Shower / WC",
      "Hair dryer",
      "Day bed",
      "Larch furniture",
      "Real wooden floor",
      "Under-floor heating",
      "Non-smoking room",
    ],
    homePageUrl: "/images/hoyu1.",
    extraImages: ["/images/hoyu2.", "/images/hoyu3."],
  },
  {
    name: ["Kofuku", "  幸福"],
    price: 200000,
    details:
      "If 3 people need to share a room, then they also need a little more space. How does 26 m2 with super-comfy box spring beds sound? This is what’s available to you at The View! The resinous scent of larch caresses your nose, the under-floor heating warms your toes, a good film on the TV provides plenty of distraction and a magnificent view is a treat for the eyes. It feels like being at home. Only better!",
    properties: [
      "26 m²",
      "Balcony",
      "Box spring bed",
      "Flat-screen TV",
      "Room safe",
      "Wireless internet",
      "Shower / WC",
      "Hair dryer",
      "Larch furniture",
      "Real wooden floor",
      "Under-floor heating",
      "Non-smoking room",
    ],
    homePageUrl: "/images/kofu1.",
    extraImages: ["/images/kofu2.", "/images/kofu3."],
  },
  {
    name: ["Yorokobi", "喜び"],
    price: 75000,
    details:
      "Holiday time at last! And it doesn’t matter at all if a passing prince comes and kisses you awake. It’s unbelievably comfortable alone in a box spring bed too! Our 18 m2 single rooms are just perfect for chilling out. For seclusion. For dreaming. When sleeping or when soaking in the landscape from the balcony. Enjoy your alone time!",
    properties: [
      "18 m²",
      "Balcony",
      "Box spring bed",
      "Flat-screen TV",
      "Room safe",
      "Wireless internet",
      "Shower / WC",
      "Hair dryer",
      "Larch furniture",
      "Real wooden floor",
      "Under-floor heating",
      "Non-smoking room",
    ],
    homePageUrl: "/images/yoro1.",
    extraImages: ["/images/yoro2.", "/images/yoro3."],
  },
];
